import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function News2() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Press release two title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Press release 2</h1>
       <p className={styles.cardDate}>31 July 2023</p>
       <p className={styles.cardCopy}>This is test content for press release two. Updated 30 July 2023.</p>
      </main>

    </div>
  )
}
