import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function News1() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Press release one title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="date" content="2023-08-15T10:00:00Z" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Press releas’ere’s 1 & α β γ</h1>
       <p className={styles.cardDate}>$7.9 billion  Martin’s Test.  Good apostrophes and bad apostrophe’s</p>
       <p className={styles.cardCopy}>Update 13 - This is test content for press release one. Updated 16 October 2023. Martins Test Update.</p>
      </main>

    </div>
  )
}
