import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function News1() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Website bot - press release test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="date" content="2023-08-15T10:00:00Z" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>$7.9 billion U.S. Army test; non- ASCII characters © à Æ; cleanse list (”|“|’|'|`)</h1>
       <p className={styles.cardDate}>$7.9 billion U.S. Army test; non ASCII characters © à Æ; cleanse list (”|“|’|'|`). £5.98</p>
       <p className={styles.cardCopy}>Updàte 13 - This is test Æcontent for press release $one. ©Updated 16 October 2023. Martin&apos;s Test Update.2″20′ 1⁄4 & ˜ ’ “</p>
      </main>

    </div>
  )
}
